class_name LootSpawner
extends Node3D
## Populates the map generated by WorldGenerator with floor-loot weapon
## pickups and POI chests. Reacts to loot_density_scale / disable_loot_spawns
## Tech rules via `density_multiplier` and `enabled`.

var world: WorldGenerator
var density_multiplier: float = 1.0
var enabled: bool = true

func setup(world_generator: WorldGenerator) -> void:
	world = world_generator

func spawn_initial_loot() -> void:
	if not enabled:
		return
	var rng := RandomNumberGenerator.new()
	rng.randomize()
	var count := int(world.loot_spawn_points.size() * density_multiplier)
	for i in count:
		var point: Vector3 = world.loot_spawn_points[i % world.loot_spawn_points.size()]
		var jitter := Vector3(rng.randf_range(-3, 3), 0, rng.randf_range(-3, 3))
		var id := WeaponDatabase.random_floor_loot_id(rng)
		var pickup := WeaponPickup.new()
		pickup.setup(id)
		add_child(pickup)
		pickup.global_position = point + jitter

	for chest_pos in world.chest_spawn_points:
		var chest := ChestNode.new()
		chest.loot_rolls = rng.randi_range(1, 3)
		add_child(chest)
		chest.global_position = chest_pos
